spring:
  application:
    name: sharding_jdbc_db_table
  datasource:
    database0:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.108.127:3306/database0?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      username: root
      password: 721000
    database1:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.108.128:3306/database1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      username: root
      password: 721000

  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

mybatis:
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.tang.read_write.domain